In [20]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU,  Bidirectional, GlobalMaxPool1D, Dropout
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.optimizers import Adam
from sklearn.metrics import roc_auc_score
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'sklearn'

In [3]:
# Input domensions and output
T = 8
D = 2
M = 3

### LSTM return state

In [4]:
X = np.random.randn(1, T, D)

In [14]:
input_ = Input(shape=(T, D))
rnn = LSTM(M, return_state=True)
x = rnn(input_)

model = Model(inputs=input_, outputs=x)

In [15]:
o, h, c = model.predict(X)

1/1 [==============================] - 1s 610ms/step


In [16]:
print("input : " , X)
print("output :", o)
print("hidden :", h)
print("cell :", c)

input :  [[[ 2.05703374 -0.94353   ]
  [-0.66893828 -0.39338693]
  [ 0.2188616   1.06320145]
  [ 1.01350239 -0.60278168]
  [-1.5198871  -0.04643683]
  [ 1.95001292  1.09170271]
  [ 0.99176862 -0.93368745]
  [ 2.12476823 -0.73377762]]]
output : [[-0.4423778  -0.25811207 -0.2046507 ]]
hidden : [[-0.4423778  -0.25811207 -0.2046507 ]]
cell : [[-0.7959183  -0.49544334 -0.39185256]]


### LSTM return sequences

In [17]:
input_ = Input(shape=(T, D))
rnn = LSTM(M, return_state=True, return_sequences=True)
# rnn = GRU(M, return_state=True)
x = rnn(input_)

In [18]:
model = Model(inputs=input_, outputs=x)
o, h, c = model.predict(X)

1/1 [==============================] - 1s 604ms/step


In [19]:
print("input : " , X)
print("output :", o)
print("hidden :", h)
print("cell :", c)

input :  [[[ 2.05703374 -0.94353   ]
  [-0.66893828 -0.39338693]
  [ 0.2188616   1.06320145]
  [ 1.01350239 -0.60278168]
  [-1.5198871  -0.04643683]
  [ 1.95001292  1.09170271]
  [ 0.99176862 -0.93368745]
  [ 2.12476823 -0.73377762]]]
output : [[[-0.17401882 -0.06990511  0.29268667]
  [-0.03552539 -0.03941612  0.1072347 ]
  [ 0.08835864 -0.00587154  0.00334775]
  [-0.09050474 -0.04651064  0.16614224]
  [ 0.14838171 -0.00531658 -0.01093786]
  [ 0.0042341  -0.02177207  0.04132164]
  [-0.1772833  -0.05969543  0.22257826]
  [-0.2965945  -0.13685454  0.40732443]]]
hidden : [[-0.2965945  -0.13685454  0.40732443]]
cell : [[-0.51004064 -0.17464851  0.81364316]]
